### ISSUE TITLE
what's the format of sample_data.src and sample_data.trg?

### ISSUE THREAD

**Issue by SeekPoint** [JayParks/tf-seq2seq#10]

**Comment by becxer** [comment]
Here is same question!

**Comment by jayparks** [comment]
<code>sample_data.src</code> and <code>sample_data.trg</code> are basically sentence-aligned parallel corpora.
I uploaded sample data (<code>sample.en</code> / <code>sample.fr</code>) at <code>/data</code> folder. please check!

**Comment by dcabz** [comment]
@JayParks  by running this command I am getting the following errors.Can you specify the exact command ?
 ./preprocess.sh sample.en sample.fr sample_data $200

normalizing punctuation..
./preprocess.sh: line 16: sample_data.sample.en: No such file or directory
./preprocess.sh: line 17: sample_data.sample.fr: No such file or directory
tokenizing..
./preprocess.sh: line 20: sample_data.norm.sample.en: No such file or directory
./preprocess.sh: line 21: sample_data.norm.sample.fr: No such file or directory
learning bpe..
cat: sample_data.tok.sample.en: No such file or directory
cat: sample_data.tok.sample.fr: No such file or directory
Traceback (most recent call last):
  File "subword_nmt/learn_bpe.py", line 186, in <module>
    threshold = max(stats.values()) / 10
ValueError: max() arg is an empty sequence
applying bpe..
./preprocess.sh: line 28: sample_data.tok.sample.en: No such file or directory
./preprocess.sh: line 29: sample_data.tok.sample.fr: No such file or directory
cleaning: filtering sequences of length over 00
clean-corpus.perl: processing sample_data.bpe.sample.en & .sample.fr to sample_data.clean, cutoff 1-00, ratio 9
Error: sample_data.bpe.sample.en does not exist at clean-corpus-n.perl line 58.
shuffling..
Traceback (most recent call last):
  File "shuffle.py", line 54, in <module>
    main(sys.argv[1:])
  File "shuffle.py", line 18, in main
    fds = [open(ff) for ff in files]
IOError: [Errno 2] No such file or directory: 'sample_data.clean.sample.en'
mv: cannot stat 'sample_data.clean.sample.en.shuf': No such file or directory
mv: cannot stat 'sample_data.clean.sample.fr.shuf': No such file or directory
building dictionaries..
Processing sample_data.shuf.sample.en
Traceback (most recent call last):
  File "build_dictionary.py", line 41, in <module>
    main()
  File "build_dictionary.py", line 16, in main
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'sample_data.shuf.sample.en'
preprocessing complete..
Traceback (most recent call last):
  File "data_statistics.py", line 16, in <module>
    main(sys.argv[1:])
  File "data_statistics.py", line 8, in main
    with open(input_file, 'r') as corpus:
IOError: [Errno 2] No such file or directory: 'sample_data.shuf.sample.en'
