### ISSUE TITLE
Can anybody provide a guidance on how to run the code? 

### ISSUE THREAD

**Issue by Jiakui** [JayParks/tf-seq2seq#2]
many thanks!

**Comment by jayparks** [comment]
Hi! I just updated README
To use the package, you should install tensorflow >= **_tf.1.2.rc1_**
If you see any issues, please open an issue or email me!

**Comment by Jiakui** [comment]
**./preprocess.sh src trg sample_data ${max_seq_len}** not working.  I will try the code on my own data. 

./preprocess.sh src trg sample_data ${max_seq_len}
normalizing punctuation..
./preprocess.sh: line 16: sample_data.src: No such file or directory
./preprocess.sh: line 17: sample_data.trg: No such file or directory
tokenizing..
./preprocess.sh: line 20: sample_data.norm.src: No such file or directory
./preprocess.sh: line 21: sample_data.norm.trg: No such file or directory
learning bpe..
cat: sample_data.tok.src: No such file or directory
cat: sample_data.tok.trg: No such file or directory
python: can't open file 'subword-nmt/learn_bpe.py': [Errno 2] No such file or directory
applying bpe..
./preprocess.sh: line 28: sample_data.tok.src: No such file or directory
./preprocess.sh: line 29: sample_data.tok.trg: No such file or directory
cleaning: filtering sequences of length over 20
clean-corpus.perl: processing sample_data.bpe.src & .trg to sample_data.clean, cutoff 1-20, ratio 9
Error: sample_data.bpe.src does not exist at clean-corpus-n.perl line 58.
shuffling..
Traceback (most recent call last):
  File "shuffle.py", line 54, in <module>
    main(sys.argv[1:])
  File "shuffle.py", line 18, in main
    fds = [open(ff) for ff in files]
IOError: [Errno 2] No such file or directory: 'sample_data.clean.src'
mv: cannot stat 'sample_data.clean.src.shuf': No such file or directory
mv: cannot stat 'sample_data.clean.trg.shuf': No such file or directory
building dictionaries..
Processing sample_data.shuf.src
Traceback (most recent call last):
  File "build_dictionary.py", line 41, in <module>
    main()
  File "build_dictionary.py", line 16, in main
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'sample_data.shuf.src'
preprocessing complete..
Traceback (most recent call last):
  File "data_statistics.py", line 16, in <module>
    main(sys.argv[1:])
  File "data_statistics.py", line 8, in main
    with open(input_file, 'r') as corpus:
IOError: [Errno 2] No such file or directory: 'sample_data.shuf.src'

**Comment by EricSites** [comment]
There is no link to the submodule subword-nmt.

**Comment by jayparks** [comment]
Hi, there was a minor mitake in subword-nmt submodule.
The issue has been solved, so please check out

**Comment by jayparks** [comment]
The preprocessing script in the README is just an example,
You need to replace each term with your own data path, data suffix and max_seq_len.
As an example, to preprocess parallel data of 'training_data.en' and 'training_data.fr' and to limit the sequence lengths to 50, the correct script should be as follows:

./preprocess.sh en fr training_data 50

**Comment by 452896915** [comment]
Where can I get the training date to generate 'training_data.en' and 'training_data.fr'?
