### ISSUE TITLE
Does the BeamSearchDecoder work well?

### ISSUE THREAD

**Issue by xueyouluo** [JayParks/tf-seq2seq#4]
Hi, I am also using r1.2 to implement beam search decoder, but I didn't get the correct results. greedy searching works well. Did you get the correct results when using beam search decoder? Thanks.

**Comment by jayparks** [comment]
BeamSearchDecoder API in r1.2.rc1 does not work well.
you should use the latest api from the master branch.
that's why i added beam_search_decoder.py file separately in my code.

**Comment by jayparks** [comment]
please see the issue#1

**Comment by xueyouluo** [comment]
I see. Thank you, I will try the new master code.
