### ISSUE TITLE
rnn moves back into core layer, should update for tf1.2?

### ISSUE THREAD

**Issue by lucasjinreal** [JayParks/tf-seq2seq#6]
Hi, this repo is userful, I just can't find a really successfully train and run implementation of seq2seq make full use of newest tensorflow apis. I check the code, seems rnn package moves back into core layer instead of contrib part. Did this tested on tensorflow1.2? Just report this to catch this repo up to the edge stage.

**Comment by jayparks** [comment]
Hi, the repo now supports tensorflow 1.2 and its core rnn layer.
Thanks for your interests!
